### ISSUE TITLE
A Qustion

### ISSUE THREAD

**Issue by aabinmadhi** [aau-zid/scheduLight#6]
Thank you aau-zid for your contribution. And wish you all the best.

My question is: I am currently working on a project to use greenlight alongside WordPress, and I came across your app. I read the instruction 3 times -my technical skills are not so great :( but I could hire a freelancer to do the job.
Does your app provide the possibility of integration with WordPress and through what file (is the api file could be linked to WordPress database?)

Regards,

**Comment by mtsonline** [comment]
Hi - your welcome.

what is your goal? (what do you mean by connecting to the wp db?)

with a little code quite everything should be possible ... 
cheers

**Comment by aabinmadhi** [comment]
My goal is to integrate WordPress and woo commerce with greenlight, in which new users are automatically created when signed up through woo commerce and a new meeting created when an order created through woo commerce.

Would that be possible giving the current app capabilities?

**Comment by mtsonline** [comment]
sure. scheduLight processing is running in the background and provides an rest api.
so all you have to do (after setting up) is another script (language of your choice) that first reads the wp db and second states the required api calls to create the meeting/users.
should not be that much work to create such a script for a developer.

of course there are other ways to realice it... either directly writing to the redis db of scheduLight instead of the api, or even taking the python classes of scheduLight and calling them with your own script.

but the api calls would be the straight way to go I guess.

hth
Martin

**Comment by aabinmadhi** [comment]
Thank you Martin for taking the time to response. 
Noted, keep up the great work.
